eyeclinic/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from reserve.views import patient_list

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reserve/', include('reserve.urls',namespace='reserve')),
]

reserve/urls.py
from django.conf.urls import url
from reserve import views

app_name = 'reserve'

urlpatterns = [
    url(r'^patient/$', views.patient_list, name='patient_list'),
    url(r'^patient/add/$', views.patient_edit, name='patient_add'),
    url(r'^patinet/mod/(?P<patient_id>\d+)/$', views.patient_edit, name='patient_mod'),
    url(r'^patient/del/(?P<patient_id>\d+)/$', views.patient_del, name='patient_del'),
    url(r'^reserve/$', views.reserve_list, name='reserve_list'),
    url(r'^reserve/add/$', views.reserve_edit, name='reserve_add'),
    url(r'^reserve/mod/(?P<reserve_id>\d+)/$', views.reserve_edit, name='reserve_mod'),
    url(r'^reserve/del/(?P<reserve_id>\d+)/$', views.reserve_del, name='reserve_del'),
]

reserve/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    SEX_CHOICES = (
        (0, '男'),
        (1, '女'),
    )

    pid = models.IntegerField()
    pname = models.CharField(max_length=20)
    pnamekana = models.CharField(max_length=50)
    birthdate = models.DateField()
    psex = models.IntegerField(choices=SEX_CHOICES)
    memo = models.TextField()

    def __str__(self):
        return self.pnamekana

class Reserve(models.Model): 
    RESERVE_TYPE = (
        (0, '手術'),
        (1, '検査'),
        (2, '術前検査'),
        (3, '診察'),
    )

    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, blank=True, null=True)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    reserve_type = models.IntegerField(choices=RESERVE_TYPE, blank=True, null=True)
    memo = models.TextField()

    def __str__(self):
        return self.id

reserve/forms.py
from django.forms import ModelForm
from reserve.models import Patient, Reserve

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ('pid', 'pname', 'pnamekana', 'birthdate', 'psex', 'memo',)
        labels = {
            'pid':'患者ID', 'pname':'氏名', 'pnamekana':'氏名カナ', 'birthdate':'生年月日', 'psex':'性別', 'memo':'備考',
        }

class ReserveForm(ModelForm):
    class Meta:
        model = Reserve
        fields = ('patient', 'start_datetime', 'end_datetime','reserve_type', 'memo',)
        labels = {
            'patient':'患者ID', 'start_datetime':'予約日時始', 'end_datetime':'予約日時終', 'reserve_type':'予約区分', 'memo':'備考',
        }

reserve/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from reserve.models import Patient, Reserve
from reserve.forms import PatientForm, ReserveForm

def patient_list(request):
    patients = Patient.objects.all().order_by('pid')
    return render(request, 
                'reserve/patient_list.html',
                {'patients':patients})

def patient_edit(request, patient_id=None):
    if patient_id:
        patient = get_object_or_404(Patient, pk=patient_id)
    else:
        patient = Patient()

    if request.method == 'POST':
        form = PatientForm(request.POST, instance=patient)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.save()
            return redirect('reserve:patient_list')
    else:
        form = PatientForm(instance=patient)

    return render(request, 'reserve/patient_edit.html', dict(form=form, patient_id=patient_id))

def patient_del(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    patient.delete()
    return redirect('reserve:patient_list')

def reserve_list(request):
    reserves = Reserve.objects.all().order_by('start_datetime')
    return render(request,
                'reserve/reserve_list.html',
                { 'reserves':reserves })

def reserve_edit(request, reserve_id=None):
    if reserve_id:
        reserve = get_object_or_404(Reserve, pk=reserve_id)
    else:
        reserve = Reserve()

    if request.method == 'POST':
        form = ReserveForm(request.POST, instance=reserve)
        if form.is_valid():
            reserve = form.save(commit=False)
            reserve.save()
            return redirect('reserve:reserve_list')
    else:
        form = ReserveForm(instance=reserve)
    return render(request, 'reserve/reserve_edit.html', dict(form=form, reserve_id=reserve_id))

def reserve_del(request, reserve_id):
    reserve = get_object_or_404(Reserve, pk=reserve_id)
    reserve.delete()
    return redirect('reserve:reserve_list')

reserve/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}eyeclinic{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block extrahead %}{% endblock %}
    </head>
    <body>
        <div class="container">
            {% block content %}
                {{ content }}
            {% endblock %}
        </div>
    </body>

</html>

reserve/templates/reserve/patient_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}患者登録{% endblock title %}

{% block content %}
    <h3 class="page-header">患者登録</h3>
    {% if patient_id %}
    <form action="{% url 'reserve:patient_mod' patient_id=patient_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'reserve:patient_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'reserve:patient_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

reserve/templates/reserve/patient_list.html
{% extends "base.html" %}

{% block title %}患者一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<h3 class="page-header">患者一覧</h3>
<a href="{% url 'reserve:patient_add' %}" class="btn btn-default btn-sm">追加</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>患者ID</th>
            <th>氏名</th>
            <th>氏名カナ</th>
            <th>生年月日</th>
            <th>性別</th>
            <th>備考</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for patient in patients %}
        <tr>
            <td>{{ patient.pid }}</td>
            <td>{{ patient.pname }}</td>
            <td>{{ patient.pnamekana }}</td>
            <td>{{ patient.birthdate }}</td>
            <td>{{ patient.psex }}</td>
            <td>{{ patient.memo }}</td>
            <td>
                <a href="{% url 'reserve:patient_mod' patient_id=patient.id %}" class="btn btn-default btn-sm">修正</a>
                <a href="{% url 'reserve:patient_del' patient_id=patient.id %}" class="btn btn-default btn-sm">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

reserve/templates/reserve/reserve_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}予約登録{% endblock title %}

{% block content %}
    <h3 class="page-header">予約登録</h3>
    {% if reserve_id %}
    <form action="{% url 'reserve:reserve_mod' reserve_id=reserve_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'reserve:reserve_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'reserve:reserve_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

reserve/templates/reserve/reserve_list.html
{% extends "base.html" %}

{% block title %}予約一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<h3 class="page-header">予約一覧</h3>
<a href="{% url 'reserve:reserve_add' %}" class="btn btn-default btn-sm">追加</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>患者ID</th>
            <th>予約日時始</th>
            <th>予約日時終</th>
            <th>予約区分</th>
            <th>備考</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for reserve in reserves %}
        <tr>
            <td>{{ reserve.patient }}</td>
            <td>{{ reserve.start_datetime }}</td>
            <td>{{ reserve.end_datetime }}</td>
            <td>{{ reserve.reserve_type }}</td>
            <td>{{ reserve.memo }}</td>
            <td>
                <a href="{% url 'reserve:reserve_mod' reserve_id=reserve.id %}" class="btn btn-default btn-sm">修正</a>
                <a href="{% url 'reserve:reserve_del' reserve_id=reserve.id %}" class="btn btn-default btn-sm">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}